"""update mails table columns

Revision ID: update_mails_columns
Revises: add_read_column
Create Date: 2026-07-28

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'update_mails_columns'
down_revision = 'add_read_column'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mails', 'sender',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mails', 'recipient',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mails', 'body',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('mails', 'sent_at',
               existing_type=mysql.DATETIME(),
               type_=mysql.DATETIME(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mails', 'sent_at',
               existing_type=mysql.DATETIME(timezone=True),
               type_=mysql.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('mails', 'body',
               existing_type=sa.String(length=1000),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('mails', 'recipient',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mails', 'sender',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
